cameras:
    camera1:
        type: perspective
        focal_length: [[16, 2], [20, 6]] # pairs of [zoom, focal len]
        vanishing_point: [-250, -250] # relative to center of screen, in pixels

lights:
    light1:
        type: directional
        origin: world
        direction: [1, 1, -1]
        diffuse: [.7, .7, .7, 1.]
        ambient: [.3, .3, .3, 1.]

sources:
    osm:
        type: MVT
        url:  http://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt

layers:
    earth:
        data: { source: osm }
        draw:
            polygons:
                order: 0
                color: [.76, .725, .66, 1.]

    landuse:
        data: { source: osm }
        draw:
            polygons:
                order: 1
                color: [0.443, 0.569, 0.4, 1.]
                interactive: true

    water:
        data: { source: osm }
        draw:
            polygons:
                order: 2
                color: [.102, .49, .569, 1.]

    roads:
        data: { source: osm }
        draw:
            lines:
                order: 4
                width: .02
                cap: round
                color: [0.41, 0.41, 0.41, 1.]
                outline:
                    width: .01
                    cap: round
                    color: [0.47, 0.47, 0.47, 1.]

    buildings:
        data: { source: osm }
        draw:
            polygons:
                order: 50
                color: [0.949, 0.941, 0.901, 1.]
                extrude: true

